M48
; DRILL file KiCad 10.0.1 date 2026-05-01T20:11:35
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-01T20:11:35-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.300
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.300
%
G90
G05
T1
X116.7Y-63.6
X117.9Y-67.6
X119.9Y-61.2
X122.2Y-64.3
T2
X118.044Y-54.761
M30
